name: markdown-toc

on:
  push:
    branches: [ "master" ]
 # workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: theboatymcboatface/markdown-toc@latest
      with:
        content-path: 'test/folder'
        document-path: 'test/README.md'
        #filter: '\(.*\).md'
      continue-on-error: true
