name: merge_requests

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:  
  
jobs:
  merge_request:
    runs-on: ubuntu-latest
    steps:
      - uses: juliangruber/merge-pull-request-action@v1
      - name: Merge Pull Request
        with:
          github-token: ${{ secrets.TOKEN }}
          number: 1
          method: squash
          repo: juliangruber/octokit-action
