name: merge_requests

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.TOKEN }}
        method: merge
        repo: theboatymcboatface/markdown-toc
