name: merge_requests

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:  
  
jobs:
runs-on: ubuntu-latest
  steps:
  - name: Merge Pull Request
    uses: juliangruber/merge-pull-request-action@v1
    with:
      github-token: ${{ secrets.TOKEN }}
      number: 1
      method: squash
      repo: juliangruber/octokit-action
