name: merge_requests

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:  
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: juliangruber/approve-pull-request-action@v2.0.0
      with:
        github-token: ${{ secrets.TOKEN }}
        number: 1
       # method: squash
       # repo: theboatymcboatface/markdown-toc
